import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {once} from 'node:events';
import {spawnSync} from 'node:child_process';
import {CorreiosService, parsePriceCents, correiosTokenExpiry} from '../src/correios.js';
import {normalizeShippingCep, validPackage, validateShippingBoxes, packRegisteredOrder} from '../src/shipping-packages.js';
import {signShippingQuote, verifyShippingQuote, SHIPPING_QUOTE_TTL_MS} from '../src/shipping-receipt.js';
import {ShippingCheckout} from '../src/shipping-checkout.js';
import {normalizeCatalog, buildOrder, calculateShipping} from '../src/catalog.js';
import {toPublicOrder} from '../src/public-order.js';
import {hashOrderRequestIntent} from '../src/order-idempotency.js';
import {readFile} from 'node:fs/promises';

// Fixtures sintéticas. As tarifas reproduzem os JSONs enviados pelo usuário;
// não são acesso ao contrato nem homologação contra os servidores dos Correios.
const T = Date.parse('2026-09-07T03:00:00Z');
const OPTIONS = {user:'fixture-user',accessCode:'ONLY_FOR_TEST_ACCESS',contract:'1234567890',originCep:'07074000'};
const PACKAGE = {weightGrams:3000,lengthCm:16,widthCm:26,heightCm:29};
const PACK = {packages:[PACKAGE],missingData:false,overweight:false};
const rate = (code='03298', priceCents=2317, days=8) => ({code,label:code==='03298'?'PAC':'SEDEX',priceCents,days,volumes:1,homeDelivery:true,deadline:'2026-09-18T23:59:59'});
function fixture(options={}) {
  const calls=[];let now=T;let auths=0;
  const fetchImpl=async(url,init)=>{
    const u=new URL(url);calls.push({url:u,init});
    if(u.pathname.includes('/token/')){auths++;return Response.json({token:`ONLY_FOR_TEST_TOKEN_${auths}`,expiraEm:new Date(now+3600000).toISOString()});}
    if(options.reply)return options.reply(u,init,calls);
    const code=u.pathname.split('/').at(-1);
    return Response.json(u.pathname.includes('/preco/')?{coProduto:code,pcFinal:code==='03298'?'23,17':'26,46'}:{coProduto:code,prazoEntrega:code==='03298'?8:4,dataMaxima:'2026-09-18T23:59:59',entregaDomiciliar:'S',entregaSabado:'N',entregaDomingo:'N'});
  };
  const service=new CorreiosService({...OPTIONS,now:()=>now,fetchImpl,...options.config});
  return {service,calls,get auths(){return auths;},advance:ms=>{now+=ms;}};
}
function catalog() {return normalizeCatalog({settings:{free:0},products:[{id:'p',name:'Pacote teste',price:5000,available:true,stock:100,boxes:[{units:1,...PACKAGE}],variants:[]}]});}
const items=[{productId:'p',variantId:'',qty:1}];
function coordinator(extra={}) {
  const calls=[];let now=T;let rates=[rate(),rate('03220',2646,4)];
  const config={shippingMode:'correios',correiosOriginCep:'07074000',correiosServices:'03298:PAC,03220:SEDEX',shippingQuoteSecret:'test-only-shipping-secret-'.repeat(3),freeShippingCents:0,...extra};
  const flow=new ShippingCheckout({config,enabled:()=>true,now:()=>now,getRates:async(context,bypass)=>{calls.push({context,bypass});return {options:structuredClone(rates)};}});
  return {flow,calls,config,setRates:r=>{rates=r;},advance:ms=>{now+=ms;}};
}
async function selected(f,service='03298',cat=catalog()){
  const q=await f.flow.quote('16503018',items,cat);const option=q.options.find(o=>o.service===service);
  return {customer:{name:'Cliente Teste',email:'fixture@example.test',phone:'11999999999'},shipping:{choice:'delivery',cep:'16503018',service,quoteToken:option.quoteToken,street:'Rua de teste',number:'1',neighborhood:'Centro',city:'Teste',state:'SP'},items:structuredClone(items),ageConfirmed:true};
}

test('CONTRACT: autentica por contrato sem exigir cartão de postagem',async()=>{const f=fixture();assert.equal(f.service.configured,true);await f.service.authenticate();assert.equal(f.calls[0].url.pathname,'/token/v1/autentica/contrato');assert.deepEqual(JSON.parse(f.calls[0].init.body),{numero:'1234567890'});assert.equal(f.calls[0].init.redirect,'error');assert.match(f.calls[0].init.headers.Authorization,/^Basic /);});
test('CONTRACT: modo cartão explícito conserva contrato e DR opcional',async()=>{const f=fixture({config:{authType:'cartaopostagem',postageCard:'1234567890',contractDr:10}});await f.service.authenticate();assert.equal(f.calls[0].url.pathname,'/token/v1/autentica/cartaopostagem');assert.deepEqual(JSON.parse(f.calls[0].init.body),{numero:'1234567890',contrato:'1234567890',dr:10});});
test('CONTRACT: configuração inválida e host não oficial não recebem credenciais',async()=>{for(const config of [{baseUrl:'https://untrusted.invalid'},{baseUrl:'http://api.correios.com.br'},{originCep:'070740001'},{services:'03298 ,bad'},{services:'03298,03298'},{authType:'usuario'},{contract:'123'}]){const f=fixture({config});assert.equal(f.service.configured,false);await assert.rejects(()=>f.service.authenticate(),{code:'CORREIOS_NOT_CONFIGURED'});assert.equal(f.calls.length,0);}});
test('TOKEN: chamadas concorrentes compartilham uma autenticação e renovam perto do vencimento',async()=>{const f=fixture();await Promise.all(Array.from({length:20},()=>f.service.authenticate()));assert.equal(f.auths,1);f.advance(3550000);await Promise.all([f.service.authenticate(),f.service.authenticate()]);assert.equal(f.auths,2);});
test('TOKEN: horário sem offset é Brasília; exp explícito limita a validade',()=>{assert.equal(correiosTokenExpiry({expiraEm:'2026-09-07T00:00:00'}),T);const token=`test.${Buffer.from(JSON.stringify({exp:T/1000})).toString('base64url')}.test`;assert.equal(correiosTokenExpiry({token,expiraEm:'2026-09-08T00:00:00Z'}),T);assert.equal(correiosTokenExpiry({token:'malformed'}),0);});
test('TOKEN: recusa resposta sem validade ou já expirada',async()=>{for(const reply of [{token:'TEST_ONLY'},{token:'TEST_ONLY',expiraEm:new Date(T-1).toISOString()},{token:'bad token',expiraEm:new Date(T+999999).toISOString()}]){const s=new CorreiosService({...OPTIONS,now:()=>T,fetchImpl:async()=>Response.json(reply)});await assert.rejects(()=>s.authenticate(),{code:'CORREIOS_TOKEN_INVALID'});}});
test('TOKEN: 401 renova uma vez; 401 persistente nunca entra em loop',async()=>{const f=fixture({reply:()=>new Response('',{status:401})});await assert.rejects(()=>f.service.authorizedRequest('/preco/v1/nacional/03298'),{code:'CORREIOS_UNAUTHORIZED'});assert.equal(f.auths,2);assert.equal(f.calls.filter(c=>c.url.pathname.includes('/preco/')).length,2);});
test('TOKEN: novo token resolve 401 e não vai para o resultado público',async()=>{let count=0;const f=fixture({reply:()=>++count===1?new Response('',{status:401}):Response.json({ok:true})});assert.deepEqual(await f.service.authorizedRequest('/test'),{ok:true});assert.equal(f.auths,2);});
test('ERROR: 403 preserva código útil sem copiar body ou credenciais',async()=>{const f=fixture({reply:()=>Response.json({error:'ONLY_FOR_TEST_ACCESS SECRET'}, {status:403})});await assert.rejects(()=>f.service.authorizedRequest('/test'),e=>e.code==='CORREIOS_FORBIDDEN'&&!e.message.includes('SECRET'));assert.equal(f.auths,1);});
test('ERROR: 429 aplica pausa curta sem bombardear o provedor',async()=>{const f=fixture({reply:()=>new Response('',{status:429})});await assert.rejects(()=>f.service.authorizedRequest('/test'));const count=f.calls.length;await assert.rejects(()=>f.service.authorizedRequest('/test'),{code:'CORREIOS_RETRY_LATER'});assert.equal(f.calls.length,count);f.advance(10001);await assert.rejects(()=>f.service.authorizedRequest('/test'));assert.equal(f.calls.length,count+1);});
test('ERROR: respostas não JSON e exageradamente grandes são recusadas',async()=>{for(const body of ['not-json',JSON.stringify({large:'a'.repeat(270000)})]){const f=fixture({reply:()=>new Response(body)});await assert.rejects(()=>f.service.authorizedRequest('/test'),{code:'CORREIOS_RESPONSE_INVALID'});}});
test('QUOTE: GET v1 reproduz separadamente PAC/SEDEX, preço e prazo sem fixar tarifa no código',async()=>{const f=fixture();const q=await f.service.quote('16503018',PACK,5000);assert.deepEqual(q.options.map(o=>[o.code,o.priceCents,o.days]),[['03298',2317,8],['03220',2646,4]]);assert.equal(f.auths,1);assert.equal(f.calls.length,5);for(const c of f.calls.filter(c=>c.url.pathname.includes('/preco/'))){assert.equal(c.init.method,'GET');assert.equal(c.url.searchParams.get('psObjeto'),'3000');assert.equal(c.url.searchParams.get('tpObjeto'),'2');assert.equal(c.url.searchParams.get('altura'),'29');for(const x of ['diametro','psCubico','servicosAdicionais','vlDeclarado'])assert.equal(c.url.searchParams.has(x),false);}assert.ok(!JSON.stringify(q).includes('ONLY_FOR_TEST'));});
test('QUOTE: cache devolve cópia independente e fechamento força reconsulta',async()=>{const f=fixture();const a=await f.service.quote('16503018',PACK);a.options[0].priceCents=1;const b=await f.service.quote('16503018',PACK);assert.equal(b.options[0].priceCents,2317);assert.equal(f.calls.length,5);await f.service.quote('16503018',PACK,0,{bypassCache:true});assert.equal(f.calls.length,9);f.advance(300001);await f.service.quote('16503018',PACK);assert.equal(f.calls.length,13);});
test('QUOTE: múltiplos volumes exigem preço de cada volume e somam em centavos',async()=>{const f=fixture();const q=await f.service.quote('16503018',{...PACK,packages:[PACKAGE,PACKAGE]});assert.equal(q.options[0].priceCents,4634);assert.equal(q.options[0].volumes,2);assert.equal(f.calls.filter(c=>c.url.pathname.includes('/preco/')).length,4);});
test('QUOTE: falta de prazo elimina serviço; PAC válido não é perdido por falha no SEDEX',async()=>{const f=fixture({reply:u=>{const code=u.pathname.split('/').at(-1);return Response.json(u.pathname.includes('/preco/')?{coProduto:code,pcFinal:'23,17'}:code==='03298'?{coProduto:code,prazoEntrega:8}:{coProduto:code,txErro:'sem prazo'});}});const q=await f.service.quote('16503018',PACK);assert.equal(q.partial,true);assert.deepEqual(q.options.map(o=>o.code),['03298']);});
test('QUOTE: faltando pcFinal, com zero, erro ou código divergente não cria opção grátis',async()=>{for(const result of [{coProduto:'03298',pcProduto:'23,17'},{coProduto:'03298',pcFinal:'0,00'},{coProduto:'03298',pcFinal:'23,17',txErro:'erro'},{coProduto:'99999',pcFinal:'23,17'}]){const f=fixture({config:{services:'03298:PAC'},reply:u=>Response.json(u.pathname.includes('/preco/')?result:{coProduto:'03298',prazoEntrega:8})});await assert.rejects(()=>f.service.quote('16503018',PACK),{code:'SHIPPING_UNAVAILABLE'});}});
test('MONEY: parser evita casas extras, exponentes e conversões silenciosas',()=>{assert.equal(parsePriceCents('1.234,56'),123456);assert.equal(parsePriceCents('26.46'),2646);assert.equal(parsePriceCents(26.46),2646);for(const value of [null,undefined,true,'','-1','0','1e3','26,461','26.461','NaN','Infinity',{},'R$ 23,17'])assert.equal(parsePriceCents(value),null);});
test('CEP: preserva zeros à esquerda e rejeita dados excedentes',()=>{assert.equal(normalizeShippingCep('07074-000'),'07074000');for(const value of ['070740000','07abc074000','00000000','12345',''])assert.equal(normalizeShippingCep(value),'');});
test('PACK: dados insuficientes ou acima do limite não chamam autenticação',async()=>{const f=fixture();for(const pack of [{...PACK,missingData:true},{...PACK,packages:[{...PACKAGE,weightGrams:30001}]},{...PACK,packages:[{...PACKAGE,lengthCm:101}]},{...PACK,packages:[]}])await assert.rejects(()=>f.service.quote('16503018',pack));assert.equal(f.calls.length,0);});
test('PACK: usa peso bruto registrado sem exigir peso inventado no produto',()=>{const cat=catalog();const p=packRegisteredOrder(items,new Map(cat.products.map(p=>[p.id,p])));assert.deepEqual(p.packages,[PACKAGE]);assert.equal(p.missingData,false);});
test('PACK: agrupamento exato e algoritmo 4+4 em vez de 6+sobra',()=>{const p={id:'p',boxes:[{units:6,...PACKAGE},{units:4,...PACKAGE}],variants:[]};const packed=packRegisteredOrder([{productId:'p',qty:3},{productId:'p',qty:5}],new Map([['p',p]]));assert.equal(packed.packages.length,2);assert.equal(packed.missingData,false);assert.equal(packRegisteredOrder([{productId:'p',qty:5}],new Map([['p',p]])).missingData,true);});
test('PACK: caixas específicas de variação prevalecem e não vazam para outra',()=>{const p={id:'p',variants:[{id:'v1'},{id:'v2'}],boxes:[{units:1,...PACKAGE},{units:1,...PACKAGE,weightGrams:4500,variantId:'v1'}]};const map=new Map([['p',p]]);assert.equal(packRegisteredOrder([{productId:'p',variantId:'v1',qty:1}],map).packages[0].weightGrams,4500);assert.equal(packRegisteredOrder([{productId:'p',variantId:'v2',qty:1}],map).packages[0].weightGrams,3000);assert.equal(packRegisteredOrder([{productId:'p',variantId:'removed',qty:1}],map).missingData,true);});
test('PACK: limite de volumes, quantidades e dimensões não são truncados',()=>{const map=new Map(catalog().products.map(p=>[p.id,p]));assert.equal(packRegisteredOrder([{productId:'p',qty:31}],map).missingData,true);for(const qty of [0,-1,1.5,1000])assert.equal(packRegisteredOrder([{productId:'p',qty}],map).missingData,true);assert.equal(validPackage({...PACKAGE,lengthCm:100,widthCm:100,heightCm:29}),false);});
test('ADMIN: caixas incompletas, duplicadas e vinculadas a variação inexistente são rejeitadas',()=>{assert.doesNotThrow(()=>validateShippingBoxes([{units:1,...PACKAGE}],[]));for(const boxes of [[{units:1,...PACKAGE,weightGrams:30001}],[{units:1,...PACKAGE,lengthCm:101}],[{units:1,...PACKAGE},{units:1,...PACKAGE}],[{units:1,...PACKAGE,variantId:'bad'}],[{units:0,...PACKAGE}]])assert.throws(()=>validateShippingBoxes(boxes,[]));});
test('ADMIN: normalização não diminui caixa inválida para fazê-la parecer válida',()=>{const c=catalog();c.products[0].boxes=[{units:1,...PACKAGE,lengthCm:101}];const normalized=normalizeCatalog(c);assert.equal(normalized.products[0].boxes[0].lengthCm,101);assert.equal(packRegisteredOrder(items,new Map(normalized.products.map(p=>[p.id,p]))).missingData,true);});
test('RECEIPT: assinatura detecta adulteração e segredo diferente',()=>{const token=signShippingQuote({service:'03298'},'test-only-secret',T);assert.equal(verifyShippingQuote(token,'test-only-secret',T).service,'03298');assert.throws(()=>verifyShippingQuote(token,'other',T),{code:'SHIPPING_QUOTE_INVALID'});const [p,s]=token.split('.');assert.throws(()=>verifyShippingQuote(`${p}.A${s.slice(1)}`,'test-only-secret',T));});
test('RECEIPT: expiração de 5 minutos e campos obrigatórios',()=>{const token=signShippingQuote({service:'03298'},'test-only-secret',T);assert.throws(()=>verifyShippingQuote(token,'test-only-secret',T+SHIPPING_QUOTE_TTL_MS),{code:'SHIPPING_QUOTE_EXPIRED'});for(const value of [null,'',{},'a'.repeat(5000)])assert.throws(()=>verifyShippingQuote(value,'test-only-secret',T),{code:'SHIPPING_QUOTE_REQUIRED'});});
test('CHECKOUT: retorna recibo sem credenciais e reconsulta a escolha no fechamento',async()=>{const f=coordinator();const body=await selected(f,'03220');body.shipping.priceCents=1;const result=await f.flow.resolve(body,catalog());assert.equal(result.priceCents,2646);assert.equal(result.service,'03220');assert.deepEqual(f.calls.map(c=>c.bypass),[false,true]);assert.deepEqual(result.packages,[PACKAGE]);assert.equal(result.originCep,'07074000');});
test('CHECKOUT: troca de CEP, quantidade, serviço, preço do catálogo ou caixa invalida recibo',async()=>{for(const change of [b=>b.shipping.cep='07074000',b=>b.items[0].qty=2,b=>b.shipping.service='03220']){const f=coordinator();const b=await selected(f);change(b);await assert.rejects(()=>f.flow.resolve(b,catalog()),{code:'SHIPPING_QUOTE_STALE'});}for(const change of [c=>c.products[0].price=6000,c=>c.products[0].boxes[0].heightCm=30]){const f=coordinator();const b=await selected(f);const c=catalog();change(c);await assert.rejects(()=>f.flow.resolve(b,c),{code:'SHIPPING_QUOTE_STALE'});}});
test('CHECKOUT: serviço indisponível não é substituído por outro mais barato',async()=>{const f=coordinator();const b=await selected(f,'03220');f.setRates([rate()]);await assert.rejects(()=>f.flow.resolve(b,catalog()),{code:'SHIPPING_SERVICE_UNAVAILABLE'});});
test('CHECKOUT: preço, prazo ou entrega domiciliar alterados exigem reconfirmação',async()=>{for(const changed of [rate('03298',2400,8),rate('03298',2317,9),{...rate(),homeDelivery:false}]){const f=coordinator();const b=await selected(f);f.setRates([changed]);await assert.rejects(()=>f.flow.resolve(b,catalog()),{code:'SHIPPING_QUOTE_CHANGED'});}});
test('CHECKOUT: recibo expirado não consulta transportadora',async()=>{const f=coordinator();const b=await selected(f);f.advance(SHIPPING_QUOTE_TTL_MS);await assert.rejects(()=>f.flow.resolve(b,catalog()),{code:'SHIPPING_QUOTE_EXPIRED'});assert.equal(f.calls.length,1);});
test('CHECKOUT: promoção legítima exige cotação e mantém custo original para a loja',async()=>{const f=coordinator({freeShippingCents:4000});const b=await selected(f);const result=await f.flow.resolve(b,catalog());assert.equal(result.priceCents,0);assert.equal(result.carrierPriceCents,2317);assert.equal(f.calls.length,2);});
test('CHECKOUT: manual deixa frete pendente mesmo com promoção de gratuidade',async()=>{const f=coordinator({freeShippingCents:1});const b=await selected(f);b.shipping.manualQuote=true;delete b.shipping.quoteToken;assert.equal(await f.flow.resolve(b,catalog()),null);const order=buildOrder(b,catalog(),f.config);assert.equal(order.requiresShippingQuote,true);assert.equal(order.shippingCents,null);});
test('ORDER: persiste modalidade/volumes; projeção pública não vaza origem, custos ou caixas',async()=>{const f=coordinator();const b=await selected(f);b.shipping.resolved=await f.flow.resolve(b,catalog());const order=buildOrder(b,catalog(),f.config);assert.equal(order.shippingCents,2317);assert.equal(order.totalCents,7317);assert.equal(order.shipping.service,'03298');assert.equal(order.requiresShippingQuote,false);const output=toPublicOrder(order);assert.equal(output.shipping.service,'03298');for(const field of ['originCep','carrierPriceCents','packages','quoteToken'])assert.equal(field in output.shipping,false);});
test('IDEMPOTENCY: serviço integra intenção; renovação de recibo não duplica pedido',()=>{const base={items,shipping:{choice:'delivery',service:'03298',quoteToken:'one',cep:'16503018'}};assert.equal(hashOrderRequestIntent(base),hashOrderRequestIntent({...base,shipping:{...base.shipping,quoteToken:'two'}}));assert.notEqual(hashOrderRequestIntent(base),hashOrderRequestIntent({...base,shipping:{...base.shipping,service:'03220'}}));});
test('SAFETY: retirada não exige credenciais e falha de envio não ganha preço zero',async()=>{const f=coordinator();assert.equal(await f.flow.resolve({shipping:{choice:'pickup'}},catalog()),null);const missing=new ShippingCheckout({config:f.config,getRates:async()=>{throw new Error('should-not-run');},enabled:()=>false});await assert.rejects(()=>missing.quote('16503018',items,catalog()),{code:'SHIPPING_NOT_CONFIGURED'});assert.equal(calculateShipping({choice:'delivery',cep:'16503018'},5000,{free:1},f.config).priceCents,null);});
test('SAFETY: rotas descartarão resolved e pagamentos bloquearão frete pendente em modo automático',async()=>{const server=await readFile(new URL('../server.js',import.meta.url),'utf8');assert.match(server,/delete cleanShipping\.resolved/);assert.match(server,/snapshot\.requiresShippingQuote && \(config\.shippingMode === 'correios'/);assert.match(server,/current\.requiresShippingQuote && \(config\.shippingMode === 'correios'/);assert.match(server,/product\?\.boxes != null\) validateShippingBoxes/);assert.ok(server.indexOf('if (snapshot.requiresShippingQuote')<server.indexOf('const reusable = reusableCheckout(snapshot)'));assert.ok(server.indexOf('if (current.requiresShippingQuote')<server.indexOf('const existing = reusableCheckout(current)'));});
test('TRANSPORT: Node HTTP local + fetch nativo executam autenticação, preço e prazo reais do código com provedor simulado',async()=>{
 const requests=[];const server=createServer(async(req,res)=>{requests.push(req.url);res.setHeader('Content-Type','application/json');const code=new URL(req.url,'http://localhost').pathname.split('/').at(-1);res.end(JSON.stringify(req.url.startsWith('/token/')?{token:'ONLY_FOR_TEST_HTTP_TOKEN',expiraEm:new Date(Date.now()+3600000).toISOString()}:req.url.startsWith('/preco/')?{coProduto:code,pcFinal:'23,17'}:{coProduto:code,prazoEntrega:8}));});server.listen(0,'127.0.0.1');await once(server,'listening');
 try{const service=new CorreiosService({...OPTIONS,baseUrl:`http://127.0.0.1:${server.address().port}`,allowTestBase:true});const q=await service.quote('16503018',PACK);assert.equal(q.options.length,2);assert.equal(requests.length,5);}finally{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}
});
test('TRANSPORT: timeout real de fetch é controlado e não reproduz detalhes internos',async()=>{const server=createServer(()=>{});server.listen(0,'127.0.0.1');await once(server,'listening');try{const service=new CorreiosService({...OPTIONS,baseUrl:`http://127.0.0.1:${server.address().port}`,allowTestBase:true,timeoutMs:50});await assert.rejects(()=>service.authenticate(),{code:'CORREIOS_TIMEOUT'});}finally{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}});

// Proteção contra combinar base de homologação com flag falso em servidor publicado.
test('CONFIG: host de homologação é detectado mesmo com flag falso e bloqueado em produção', () => {
 const moduleUrl=new URL('../src/config.js',import.meta.url).href;
 const result=spawnSync(process.execPath,['--input-type=module','-e',`import {config,assertProductionConfig} from ${JSON.stringify(moduleUrl)};let blocked=false;try{assertProductionConfig();}catch(e){blocked=e.message.includes('CORREIOS_HOMOLOG=false');}console.log(JSON.stringify({homolog:config.correiosHomolog,blocked}));`],{encoding:'utf8',env:{...process.env,NODE_ENV:'production',SHIPPING_MODE:'correios',CORREIOS_BASE_URL:'https://apihom.correios.com.br/',CORREIOS_HOMOLOG:'false'}});
 assert.equal(result.status,0,result.stderr);assert.deepEqual(JSON.parse(result.stdout),{homolog:true,blocked:true});
});
